"""add_external_code_to_products_and_suppliers

Revision ID: 2a2936c1cb87
Revises: 1c0a8f3d0314
Create Date: 2026-06-25 16:27:57.551933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a2936c1cb87'
down_revision: Union[str, Sequence[str], None] = '1c0a8f3d0314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('external_code', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'products', ['external_code'])
    op.add_column('suppliers', sa.Column('external_code', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'suppliers', ['external_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_column('suppliers', 'external_code')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'external_code')
    # ### end Alembic commands ###
