"""invoice_products_table

Revision ID: 839427545057
Revises: ce5e9ceb7a74
Create Date: 2026-07-13 16:30:19.124349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839427545057'
down_revision: Union[str, Sequence[str], None] = 'ce5e9ceb7a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Créer la table invoice_products
    op.create_table('invoice_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Migrer les données existantes
    op.execute("""
        INSERT INTO invoice_products (id, invoice_id, product_id)
        SELECT gen_random_uuid(), id, product_id FROM invoices WHERE product_id IS NOT NULL
    """)
    # Supprimer l'ancienne colonne
    op.drop_constraint('invoices_product_id_fkey', 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'product_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('invoices_product_id_fkey'), 'invoices', 'products', ['product_id'], ['id'])
    op.drop_table('invoice_products')
    # ### end Alembic commands ###
