"""add_product_schema_image

Revision ID: ce5e9ceb7a74
Revises: cdf3332a5b92
Create Date: 2026-07-13 10:03:21.431967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce5e9ceb7a74'
down_revision: Union[str, Sequence[str], None] = 'cdf3332a5b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('schema_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'schema_image_url')
    # ### end Alembic commands ###
